const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function getType(title) {
  const lowerTitle = title.toLowerCase();
  if (lowerTitle.includes('security') || lowerTitle.includes('secure') || lowerTitle.includes('harden') || lowerTitle.includes('oauth security') || lowerTitle.includes('cors security')) {
    return 'security';
  }

  const prefixMatch = title.match(/^([a-zA-Z]+)(?:\([^)]+\))?:/);
  if (prefixMatch) {
    const prefix = prefixMatch[1].toLowerCase();
    switch (prefix) {
      case 'feat': return 'added';
      case 'fix': return 'fixed';
      case 'refactor': return 'changed';
      case 'perf': return 'changed';
      case 'style': return 'changed';
      case 'test': return 'test';
      case 'chore': return 'maintenance';
      case 'build': return 'maintenance';
      case 'ci': return 'maintenance';
      case 'docs': return 'docs';
    }
  }
  return 'changed';
}

function generateChangelog() {
  const delimiter = '|||---DELIMITER---|||';
  const format = `%H%n%h%n%cI%n%s%n%b${delimiter}`;
  let gitOutput = '';
  try {
    gitOutput = execSync(`git log main --format="${format}"`).toString('utf8');
  } catch (error) {
    console.error('Failed to run git log:', error.message);
    process.exit(1);
  }

  const commits = [];
  const entries = gitOutput.split(delimiter).filter(entry => entry.trim() !== '');

  for (const entry of entries) {
    const lines = entry.trim().split('\n');
    if (lines.length >= 4) {
      const sha = lines[0];
      const shortSha = lines[1];
      const timestamp = lines[2];
      const title = lines[3];
      const body = lines.slice(4).join('\n').trim();

      const type = getType(title);

      commits.push({
        sha,
        shortSha,
        timestamp,
        title,
        body,
        type,
        url: `https://github.com/ItsCryp7iC/travelers-toolkit/commit/${sha}`
      });
    }
  }

  const fileContent = `// AUTO-GENERATED by scripts/generate_changelog.cjs
// Do not edit manually.

export const changelogEntries = ${JSON.stringify(commits, null, 2)};
`;

  const outputPath = path.join(__dirname, '..', 'src', 'data', 'changelog.js');
  fs.writeFileSync(outputPath, fileContent, 'utf8');
  console.log(`Generated changelog with ${commits.length} commits.`);
}

generateChangelog();
